SCREEN_WIDTH = 900
SCREEN_HEIGHT = 700

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
BLUE = (0, 0, 255)

BACKGROUND_COLOR = WHITE

# Defense line
DEFENSE_LINE_WIDTH = 25
DEFENSE_LINE_POS_X = 150
DEFENSE_LINE_COLOR = BLACK

# HP
HP_WIDTH = 30
HP_HEIGHT = 30
HP_POS_X = SCREEN_WIDTH - 50
HP_POS_Y = 50 - HP_HEIGHT
HP_COLOR = RED

# Player
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
INITIAL_PLAYER_POS_X = 25
INITIAL_PLAYER_POS_Y = SCREEN_HEIGHT / 2
PLAYER_SPEED = 5

# Enemy A
ENEMY_A_WIDTH = 50
ENEMY_A_HEIGHT = 50
ENEMY_A_SPEED = 1
ENEMY_A_HEALTH = 2
ENEMY_A_COLOR = RED

# Enemy B
ENEMY_B_WIDTH = 60
ENEMY_B_HEIGHT = 60
ENEMY_B_SPEED = 1.5
ENEMY_B_HEALTH = 1
ENEMY_B_COLOR = BLUE

# Projectile
PROJECTILE_SPEED = 6
PROJECTILE_DAMAGE = 1
INITIAL_PROJECTILE_COOLDOWN = 750 # milliseconds
projectile_cooldown = INITIAL_PROJECTILE_COOLDOWN
PROJECTILE_WIDTH = 20
PROJECTILE_HEIGHT = 10
PROJECTILE_COLOR = BLACK